### ISSUE TITLE
Links to the design articles are broken

### ISSUE THREAD

**Issue by dtoomey** [Azure/Integration-Services-Landing-Zone-Accelerator#31]
The recent reorganisation (commit # [8cdd84d](https://github.com/Azure/Integration-Services-Landing-Zone-Accelerator/commit/8cdd84d8ad9e8c402c52329c493ab59df6dccfd0)) has broken all the links in the table on the main [ReadMe page](https://github.com/Azure/Integration-Services-Landing-Zone-Accelerator/blob/main/README.md).  The docs were moved from the root of the _/docs_ folder into the _/scenario1_ folder, but the links were not updated.

Personally, I'm not sure why they were moved? The concepts discussed within these excellent pages would apply to all scenarios. Burying them under a specific scenario page makes them harder to find (especially when the links on the landing page don't take you there. ;-) )

**Comment by briggsb9** [comment]
Looking at the contents I agree, and assume this was done in error or to prep for a future change. @kunalbabre 

For now lets move it back with #32 (?)
